#define DK_AE KC_SCLN
#define DK_OSTR KC_QUOT
#define DK_COMM KC_COMM
#define DK_DOT KC_DOT
#define DK_QUOT KC_NUHS
#define DK_ARNG KC_LBRC
#define DK_LABK KC_NUBS
#define DK_RABK S(KC_NUBS)
#define DK_DQUO S(KC_2)
#define DK_GRV S(KC_EQL)
#define DK_EXLM S(KC_1)
#define DK_MINS KC_SLSH
#define DK_PLUS KC_MINS
#define DK_EQL S(KC_0)
#define DK_QUES S(KC_MINS)
#define DK_CIRC S(KC_RBRC)
#define DK_SLSH S(KC_7)
#define DK_ASTR S(KC_NUHS)
#define DK_BSLS ALGR(KC_NUBS)
#define DK_AMPR S(KC_6)
#define DK_AT ALGR(KC_2)
#define DK_LCBR ALGR(KC_7)
#define DK_RCBR ALGR(KC_0)
#define DK_PERC S(KC_5)
#define DK_TILD ALGR(KC_RBRC)
#define DK_HASH S(KC_3)
#define DK_LPRN S(KC_8)
#define DK_RPRN S(KC_9)
#define DK_UNDS S(KC_SLSH)
#define DK_PIPE ALGR(KC_EQL)
#define DK_DLR ALGR(KC_4)
#define DK_LBRC ALGR(KC_8)
#define DK_RBRC ALGR(KC_9)
#define KC_PC_UNDO LCTL(KC_Z)
#define KC_PC_CUT LCTL(KC_X)
#define KC_PC_COPY LCTL(KC_C)
#define KC_PC_PASTE LCTL(KC_V)
