CONSOLE_ENABLE = no
COMMAND_ENABLE = no
### Enable again later (maybe)
# ORYX_ENABLE = yes
# RGB_MATRIX_CUSTOM_KB = yes
DYNAMIC_MACRO_ENABLE = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes

KEY_OVERRIDE_ENABLE = yes

COMBO_ENABLE = yes

LAYER_LOCK_ENABLE = yes
